(function(EA){'use strict';var $=function(id){return document.getElementById(id);},storage=new EA.Storage(),game,renderer=new EA.Renderer($('arena')),timer=null,champion=storage.load('champion',null),lessMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
  var education={linear:'A reta mantém inclinação constante: o coeficiente controla subida ou descida.',quadratica:'A parábola curva progressivamente por causa do termo ao quadrado.',cubica:'A cúbica limitada permite mudanças de curvatura sem coordenadas extremas.',senoide:'A senoide oscila; amplitude e frequência moldam ondas repetidas.',cossenoide:'O cosseno cria oscilação com fase inicial diferente da senoide.',balistica:'O arco combina velocidade vertical e gravidade simulada.',hibrida:'A trajetória híbrida combina oscilação e curvatura.'};
  function toast(s){$('toast').textContent=s;$('toast').className='show';setTimeout(function(){$('toast').className='';},2600);}
  function seed(){return 'EA-'+Date.now().toString(36).toUpperCase();}
  function read(){var fam=Array.prototype.filter.call(document.querySelectorAll('[name=family]'),function(x){return x.checked;}).map(function(x){return x.value;});return{seed:$('seed').value.trim()||seed(),mode:$('mode').value,botsA:+$('botsA').value,botsB:+$('botsB').value,strategyA:$('strategyA').value,strategyB:$('strategyB').value,hp:+$('hp').value,damage:+$('damage').value,width:+$('width').value,obstacles:+$('obstacles').value,turnLimit:+$('turnLimit').value,population:+$('population').value,generations:+$('generations').value,mutation:+$('mutation').value,friendlyFire:$('friendlyFire').checked,families:fam};}
  function write(c){Object.keys(c).forEach(function(k){var e=$(k);if(!e)return;if(e.type==='checkbox')e.checked=Boolean(c[k]);else e.value=c[k];});document.querySelectorAll('[name=family]').forEach(function(x){x.checked=(c.families||EA.EQUATION_FAMILIES).indexOf(x.value)>=0;});}
  function update(){if(!game)return;renderer.animate(game);$('seedDisplay').textContent=game.config.seed;$('turn').textContent=String(game.turn).padStart(2,'0')+' / '+game.config.turnLimit;$('scoreA').textContent=game.living('A').length+' ativos · '+game.living('A').reduce(function(s,b){return s+b.hp;},0)+' PV';$('scoreB').textContent=game.living('B').length+' ativos · '+game.living('B').reduce(function(s,b){return s+b.hp;},0)+' PV';var c=game.current;if(c){$('shooter').textContent=c.bot.name+' · '+EA.Strategies[c.bot.strategy].name;$('target').textContent='Alvo: '+c.target.name+' · '+EA.familyLabel(c.choice.equation.family);$('equation').textContent=c.choice.equation.text();$('result').textContent=c.result.reason+(c.dealt?' · '+c.dealt+' dano':'');$('education').textContent=education[c.choice.equation.family];if(c.bot.evolution){$('generation').textContent=c.bot.evolution.generation;$('fitness').textContent=c.bot.evolution.bestFitness.toFixed(1);$('meanFitness').textContent=c.bot.evolution.meanFitness.toFixed(1);}$('arenaDescription').textContent='Turno '+game.turn+'. '+c.bot.name+' disparou contra '+c.target.name+'. Resultado: '+c.result.reason+'.';}if(game.finished){$('shooter').textContent=game.winner==='Empate'?'Empate técnico':'Time '+game.winner+' venceu';$('target').textContent='Batalha concluída após '+game.turn+' turnos.';}renderLog();}
  function renderLog(){var list=$('log'),start=Math.max(0,game.history.length-10),i,li;list.textContent='';for(i=game.history.length-1;i>=start;i-=1){li=document.createElement('li');li.textContent='#'+game.history[i].turn+' '+game.history[i].bot+' → '+game.history[i].result+(game.history[i].damage?' ('+game.history[i].damage+' dano)':'');list.appendChild(li);}}
  function loop(){if(timer)clearTimeout(timer);if(!game||game.paused||game.finished)return;game.step();update();timer=setTimeout(loop,lessMotion?180:Math.max(55,620/game.config.speed));}
  function start(){if(timer)clearTimeout(timer);game=new EA.GameEngine(read());$('seed').value=game.config.seed;storage.save('config',game.config);renderer.resize(game.arena);update();if(game.config.mode==='torneio'){runTournament();return;}if(game.config.mode==='laboratorio'){game.config.strategyA='evolution';game.config.strategyB='analytical';toast('Laboratório ativo: evolução observável e pausável.');}if(game.config.mode!=='passo'){game.paused=false;loop();}else toast('Modo passo a passo: use “Próximo turno”.');}
  function runTournament(){var cfg=read(),rows={A:0,B:0,Empate:0},sum={damageA:0,damageB:0,hitsA:0,hitsB:0,killsA:0,killsB:0},i,g;for(i=0;i<cfg.tournamentGames;i+=1){cfg.seed=game.config.seed+'-T'+i;if(i%2){var s=cfg.strategyA;cfg.strategyA=cfg.strategyB;cfg.strategyB=s;}g=new EA.GameEngine(cfg);g.runFast();rows[g.winner]+=1;sum.damageA+=g.teamStats.A.damage;sum.damageB+=g.teamStats.B.damage;sum.hitsA+=g.teamStats.A.hits;sum.hitsB+=g.teamStats.B.hits;sum.killsA+=g.teamStats.A.kills;sum.killsB+=g.teamStats.B.kills;}game=g;$('tournament').textContent='Vitórias A: '+rows.A+' · B: '+rows.B+' · Empates: '+rows.Empate+' | Dano A/B: '+sum.damageA+'/'+sum.damageB+' · Acertos: '+sum.hitsA+'/'+sum.hitsB+' · Eliminações: '+sum.killsA+'/'+sum.killsB;renderer.resize(game.arena);update();storage.save('tournament',{wins:rows,stats:sum});}
  function download(name,text,type){var a=document.createElement('a'),blob=new Blob([text],{type:type||'application/json'});a.href=URL.createObjectURL(blob);a.download=name;document.body.appendChild(a);a.click();a.remove();setTimeout(function(){URL.revokeObjectURL(a.href);},500);}
  EA.EQUATION_FAMILIES.forEach(function(f){var l=document.createElement('label'),x=document.createElement('input');x.type='checkbox';x.name='family';x.value=f;x.checked=true;l.appendChild(x);l.appendChild(document.createTextNode(' '+EA.familyLabel(f)));$('families').appendChild(l);});write(storage.load('config',EA.DEFAULTS));
  $('configForm').addEventListener('submit',function(e){e.preventDefault();start();});$('pause').onclick=function(){game.paused=true;toast('Simulação pausada.');};$('resume').onclick=function(){game.paused=false;loop();};$('next').onclick=function(){game.paused=true;game.step(true);update();};$('restart').onclick=function(){write(game.config);start();};$('newSeed').onclick=function(){$('seed').value=seed();start();};$('accelerate').onclick=function(){game.config.speed=EA.clamp(game.config.speed*2,.25,8);toast('Velocidade: '+game.config.speed+'×');if(!game.paused)loop();};$('lab').onclick=function(){$('mode').value='laboratorio';$('strategyA').value='evolution';start();};$('defaults').onclick=function(){write(EA.DEFAULTS);toast('Configurações restauradas.');};$('copySeed').onclick=function(){var s=game?game.config.seed:$('seed').value;if(navigator.clipboard&&navigator.clipboard.writeText)navigator.clipboard.writeText(s);toast('Seed copiada: '+s);};
  $('saveChampion').onclick=function(){var bots=game.bots.filter(function(b){return b.evolution&&b.evolution.best;});if(!bots.length){toast('Ainda não há campeão evolutivo.');return;}champion=bots[0].evolution.best;storage.save('champion',champion);toast(storage.available?'Campeão salvo localmente.':'Campeão salvo apenas nesta sessão; armazenamento indisponível.');};$('export').onclick=function(){download('equation-arena-'+game.config.seed+'.json',EA.exportState(game,champion));};$('report').onclick=function(){download('relatorio.txt','Equation Arena\nSeed: '+game.config.seed+'\nTurnos: '+game.turn+'\nVencedor: '+game.winner+'\nDano A/B: '+game.teamStats.A.damage+'/'+game.teamStats.B.damage,'text/plain');};$('import').onclick=function(){$('importFile').click();};$('importFile').onchange=function(){var file=this.files[0],reader;if(!file)return;reader=new FileReader();reader.onload=function(){try{var data=EA.validateImport(reader.result);write(data.config);$('seed').value=data.seed;champion=data.champion||champion;start();toast('Dados validados e importados.');}catch(e){toast('Importação rejeitada: '+e.message);}};reader.readAsText(file);};$('clear').onclick=function(){storage.clear();game.history=[];renderLog();toast('Histórico local limpo.');};
  function renderFrame(){if(game)renderer.animate(game);window.requestAnimationFrame(renderFrame);}
  window.addEventListener('resize',function(){if(game)renderer.resize(game.arena);});document.addEventListener('visibilitychange',function(){if(document.hidden&&game){game.paused=true;toast('Pausa automática: aba inativa.');}});start();window.requestAnimationFrame(renderFrame);
}(window.EA));
