(function(EA){'use strict';function EvolutionEngine(cfg,rng){this.rng=rng;this.size=EA.clamp(cfg.population,8,80);this.rate=EA.clamp(cfg.mutation,.01,.8);this.population=[];this.generation=0;this.bestFitness=-Infinity;this.meanFitness=0;this.best=null;}
  EvolutionEngine.prototype.randomGenome=function(families){var f=this.rng.pick(families);return{family:f,genes:[this.rng.range(-80,80),this.rng.range(-8,24),this.rng.range(-3,3)],domain:this.rng.range(250,750),mutation:this.rate,fitness:-Infinity};};
  EvolutionEngine.prototype.ensure=function(families){while(this.population.length<this.size)this.population.push(this.randomGenome(families));};
  EvolutionEngine.prototype.toEquation=function(g,s,d){return EA.makeEquation(g.family,s,d,g.genes,g.domain);};
  EvolutionEngine.prototype.evaluate=function(g,ctx){try{var e=this.toEquation(g,ctx.shooter,ctx.direction),r=EA.simulateShot(e,ctx.arena,ctx.bots,ctx.bot,ctx.friendlyFire),complex=g.genes.reduce(function(n,v){return n+Math.abs(v);},0)*.015;g.fitness=1000/(1+r.minDistance)+(r.hit&&r.hit.team!==ctx.bot.team?1800:0)+(r.hit&&r.hit.team===ctx.bot.team?-900:0)-(r.reason==='obstáculo'?150:0)-(r.reason==='fora da arena'&&r.path.length<8?200:0)-complex;return g.fitness;}catch(ignore){g.fitness=-2000;return g.fitness;}};
  EvolutionEngine.prototype.tournament=function(){var a=this.rng.pick(this.population),b=this.rng.pick(this.population),c=this.rng.pick(this.population);return [a,b,c].sort(function(x,y){return y.fitness-x.fitness;})[0];};
  EvolutionEngine.prototype.crossover=function(a,b){var self=this,g={family:this.rng.next()<.5?a.family:b.family,genes:a.genes.map(function(v,i){return self.rng.next()<.5?v:b.genes[i];}),domain:(a.domain+b.domain)/2,mutation:(a.mutation+b.mutation)/2,fitness:-Infinity};return g;};
  EvolutionEngine.prototype.mutate=function(g,families){var self=this,c={family:g.family,genes:g.genes.slice(),domain:g.domain,mutation:g.mutation,fitness:-Infinity};c.genes=c.genes.map(function(v){return EA.clamp(v+(self.rng.next()<c.mutation?self.rng.gaussian()*12:0),-500,500);});if(this.rng.next()<c.mutation*.08)c.family=this.rng.pick(families);c.domain=EA.clamp(c.domain+(this.rng.next()<c.mutation?this.rng.gaussian()*35:0),30,1200);return c;};
  EvolutionEngine.prototype.step=function(ctx,families){var i,next;this.ensure(families);for(i=0;i<this.population.length;i+=1)this.evaluate(this.population[i],ctx);this.population.sort(function(a,b){return b.fitness-a.fitness;});this.best=this.population[0];this.bestFitness=Math.max(this.bestFitness,this.best.fitness);this.meanFitness=this.population.reduce(function(s,g){return s+g.fitness;},0)/this.size;next=[this.population[0],this.population[1]];while(next.length<this.size)next.push(this.mutate(this.crossover(this.tournament(),this.tournament()),families));this.population=next;this.generation+=1;return this.best;};
  EvolutionEngine.prototype.run=function(n,ctx,families){var best,i;for(i=0;i<EA.clamp(n,1,30);i+=1)best=this.step(ctx,families);return best;};EA.EvolutionEngine=EvolutionEngine;
}(window.EA));
