(function(EA){'use strict';var defaults={seed:'equation-arena',mode:'exibicao',botsA:6,botsB:6,strategyA:'analytical',strategyB:'evolution',hp:100,damage:34,width:900,obstacles:3,families:EA.EQUATION_FAMILIES.slice(),speed:1,turnLimit:160,friendlyFire:false,population:24,generations:4,mutation:.16,tournamentGames:6};
  function clean(c){c=c||{};return{seed:String(c.seed||defaults.seed).slice(0,60),mode:['exibicao','torneio','laboratorio','passo'].indexOf(c.mode)>=0?c.mode:defaults.mode,botsA:EA.clamp(c.botsA||6,1,20),botsB:EA.clamp(c.botsB||6,1,20),strategyA:EA.Strategies[c.strategyA]?c.strategyA:defaults.strategyA,strategyB:EA.Strategies[c.strategyB]?c.strategyB:defaults.strategyB,hp:EA.clamp(c.hp||100,20,300),damage:EA.clamp(c.damage||34,5,100),width:EA.clamp(c.width||900,600,1200),obstacles:EA.clamp(c.obstacles===undefined?3:c.obstacles,0,8),families:Array.isArray(c.families)&&c.families.length?c.families.filter(function(f){return EA.EQUATION_FAMILIES.indexOf(f)>=0;}):defaults.families.slice(),speed:EA.clamp(c.speed||1,.25,8),turnLimit:EA.clamp(c.turnLimit||160,5,800),friendlyFire:Boolean(c.friendlyFire),population:EA.clamp(c.population||24,8,80),generations:EA.clamp(c.generations||4,1,30),mutation:EA.clamp(c.mutation||.16,.01,.8),tournamentGames:EA.clamp(c.tournamentGames||6,2,20)};}
  function GameEngine(cfg){this.config=clean(cfg);this.reset();}
  GameEngine.prototype.reset=function(){this.rng=new EA.PRNG(this.config.seed);this.arena=new EA.Arena(this.config,this.rng);this.bots=this.arena.createBots(this.config,this.rng);this.turn=0;this.cursor=-1;this.paused=this.config.mode==='passo';this.finished=false;this.winner=null;this.history=[];this.current=null;this.teamStats={A:{damage:0,hits:0,kills:0},B:{damage:0,hits:0,kills:0}};return this;};
  GameEngine.prototype.living=function(team){return this.bots.filter(function(b){return b.alive&&(!team||b.team===team);});};
  GameEngine.prototype.nextBot=function(){var i;for(i=0;i<this.bots.length;i+=1){this.cursor=(this.cursor+1)%this.bots.length;if(this.bots[this.cursor].alive)return this.bots[this.cursor];}return null;};
  GameEngine.prototype.targetFor=function(bot){var enemies=this.living(bot.team==='A'?'B':'A');return enemies.sort(function(a,b){return EA.distance(bot,a)-EA.distance(bot,b);})[0]||null;};
  GameEngine.prototype.teamSnapshot=function(team){var living=this.living(team),initial=team==='A'?this.config.botsA:this.config.botsB;return{team:team,initial:initial,living:living.length,eliminated:initial-living.length,hp:living.reduce(function(sum,bot){return sum+bot.hp;},0)};};
  GameEngine.prototype.scoreText=function(team){var s=this.teamSnapshot(team);return s.living+'/'+s.initial+' ativos · '+s.hp+' PV · '+s.eliminated+' eliminados';};
  GameEngine.prototype.resolve=function(){var a=this.living('A'),b=this.living('B'),sa=this.teamStats.A,sb=this.teamStats.B,hpa=a.reduce(function(s,x){return s+x.hp;},0),hpb=b.reduce(function(s,x){return s+x.hp;},0);if(!a.length||!b.length||this.turn>=this.config.turnLimit){this.finished=true;if(hpa!==hpb)this.winner=hpa>hpb?'A':'B';else if(sa.damage!==sb.damage)this.winner=sa.damage>sb.damage?'A':'B';else if(sa.hits!==sb.hits)this.winner=sa.hits>sb.hits?'A':'B';else this.winner='Empate';return true;}return false;};
  GameEngine.prototype.step=function(force){if(this.finished||(!force&&this.paused))return null;if(this.resolve())return null;var bot=this.nextBot(),target=this.targetFor(bot),choice,result,dealt=0;if(!bot||!target){this.resolve();return null;}choice=EA.Strategies[bot.strategy].choose(bot,target,this);if(!target.alive){target=this.targetFor(bot);if(!target){this.resolve();return null;}choice=EA.Strategies[bot.strategy].choose(bot,target,this);}result=EA.simulateShot(choice.equation,this.arena,this.bots,bot,this.config.friendlyFire);bot.shots+=1;bot.lastEquation=choice.equation.text();bot.distanceTotal+=result.minDistance;if(result.hit){dealt=result.hit.applyDamage(this.config.damage);bot.damage+=dealt;if(result.hit.team!==bot.team){bot.hits+=1;this.teamStats[bot.team].hits+=1;}this.teamStats[bot.team].damage+=dealt;if(!result.hit.alive){bot.kills+=1;this.teamStats[bot.team].kills+=1;}}bot.memory.push({verticalError:target.y-result.impact.y,distance:result.minDistance});if(bot.memory.length>12)bot.memory.shift();this.turn+=1;this.current={bot:bot,target:target,choice:choice,result:result,dealt:dealt};this.history.push({turn:this.turn,bot:bot.name,target:target.name,equation:choice.equation.text(),family:choice.equation.family,result:result.reason,distance:Math.round(result.minDistance),damage:dealt,fitness:choice.fitness||null});this.resolve();if(this.config.mode==='passo')this.paused=true;return this.current;};
  GameEngine.prototype.runFast=function(){var guard=0,limit=this.config.turnLimit+2;this.paused=false;while(!this.finished&&guard<limit){this.step(true);guard+=1;}return this.winner;};
  EA.chaoticConfig=function(config){var result=Object.assign({},config||{});result.botsA=10;result.botsB=10;result.turnLimit=Math.max(Number(result.turnLimit)||0,240);result.width=Math.max(Number(result.width)||0,900);result.obstacles=4;return clean(result);};
  EA.DEFAULTS=defaults;EA.cleanConfig=clean;EA.GameEngine=GameEngine;
}(window.EA));
