(function(EA){'use strict';var mapTypes=['planicie','fortaleza','canion','ilhas','arena','caos','aleatorio'],spawnModes=['frentes','espalhado','squads','cerco','caos'],archetypeModes=['aleatoria','equilibrada','uniforme','personalizada'],defaults={seed:'equation-arena',mode:'exibicao',botsA:6,botsB:6,strategyA:'analytical',strategyB:'evolution',archetypeModeA:'equilibrada',archetypeModeB:'equilibrada',archetypeA:'commander',archetypeB:'commander',mapType:'aleatorio',density:'media',spawnMode:'frentes',hp:100,damage:34,width:1200,obstacles:8,families:EA.EQUATION_FAMILIES.slice(),speed:1,turnLimit:240,friendlyFire:false,population:24,generations:4,mutation:.16,tournamentGames:6};
  function allowed(value,list,fallback){return list.indexOf(value)>=0?value:fallback;}
  function clean(c){c=c||{};return{seed:String(c.seed||defaults.seed).slice(0,60),mode:allowed(c.mode,['exibicao','torneio','laboratorio','passo'],defaults.mode),botsA:EA.clamp(c.botsA||6,1,40),botsB:EA.clamp(c.botsB||6,1,40),strategyA:EA.Strategies[c.strategyA]?c.strategyA:defaults.strategyA,strategyB:EA.Strategies[c.strategyB]?c.strategyB:defaults.strategyB,archetypeModeA:allowed(c.archetypeModeA,archetypeModes,defaults.archetypeModeA),archetypeModeB:allowed(c.archetypeModeB,archetypeModes,defaults.archetypeModeB),archetypeA:EA.ARCHETYPES[c.archetypeA]?c.archetypeA:defaults.archetypeA,archetypeB:EA.ARCHETYPES[c.archetypeB]?c.archetypeB:defaults.archetypeB,mapType:allowed(c.mapType,mapTypes,defaults.mapType),density:allowed(c.density,['baixa','media','alta','extrema'],defaults.density),spawnMode:allowed(c.spawnMode,spawnModes,defaults.spawnMode),hp:EA.clamp(c.hp||100,20,300),damage:EA.clamp(c.damage||34,5,100),width:EA.clamp(c.width||1200,700,2000),obstacles:EA.clamp(c.obstacles===undefined?8:c.obstacles,0,24),families:Array.isArray(c.families)&&c.families.length?c.families.filter(function(f){return EA.EQUATION_FAMILIES.indexOf(f)>=0;}):defaults.families.slice(),speed:EA.clamp(c.speed||1,.25,8),turnLimit:EA.clamp(c.turnLimit||240,5,1200),friendlyFire:Boolean(c.friendlyFire),population:EA.clamp(c.population||24,8,80),generations:EA.clamp(c.generations||4,1,30),mutation:EA.clamp(c.mutation||.16,.01,.8),tournamentGames:EA.clamp(c.tournamentGames||6,2,20)};}
  function GameEngine(cfg){this.config=clean(cfg);this.reset();}
  GameEngine.prototype.reset=function(){this.rng=new EA.PRNG(this.config.seed);this.arena=new EA.Arena(this.config,this.rng);this.bots=this.arena.createBots(this.config,this.rng);this.turn=0;this.cursor=-1;this.paused=this.config.mode==='passo';this.finished=false;this.winner=null;this.history=[];this.current=null;this.teamStats={A:{damage:0,hits:0,kills:0},B:{damage:0,hits:0,kills:0}};return this;};
  GameEngine.prototype.living=function(team){return this.bots.filter(function(b){return b.alive&&(!team||b.team===team);});};
  GameEngine.prototype.nextBot=function(){var i;for(i=0;i<this.bots.length;i+=1){this.cursor=(this.cursor+1)%this.bots.length;if(this.bots[this.cursor].alive)return this.bots[this.cursor];}return null;};
  GameEngine.prototype.targetFor=function(bot){var enemies=this.living(bot.team==='A'?'B':'A'),commander;if(!enemies.length)return null;if(bot.archetype!=='commander'){commander=this.living(bot.team).filter(function(ally){return ally.archetype==='commander'&&EA.distance(bot,ally)<190;})[0];}return EA.rankTargets(commander||bot,enemies,this.rng)[0];};
  GameEngine.prototype.teamSnapshot=function(team){var living=this.living(team),initial=team==='A'?this.config.botsA:this.config.botsB;return{team:team,initial:initial,living:living.length,eliminated:initial-living.length,hp:living.reduce(function(sum,bot){return sum+bot.hp;},0)};};
  GameEngine.prototype.scoreText=function(team){var s=this.teamSnapshot(team);return s.living+'/'+s.initial+' ativos · '+s.hp+' PV · '+s.eliminated+' eliminados';};
  GameEngine.prototype.resolve=function(){var a=this.living('A'),b=this.living('B'),sa=this.teamStats.A,sb=this.teamStats.B,hpa=a.reduce(function(s,x){return s+x.hp;},0),hpb=b.reduce(function(s,x){return s+x.hp;},0);if(!a.length||!b.length||this.turn>=this.config.turnLimit){this.finished=true;if(hpa!==hpb)this.winner=hpa>hpb?'A':'B';else if(sa.damage!==sb.damage)this.winner=sa.damage>sb.damage?'A':'B';else if(sa.hits!==sb.hits)this.winner=sa.hits>sb.hits?'A':'B';else this.winner='Empate';return true;}return false;};
  GameEngine.prototype.step=function(force){if(this.finished||(!force&&this.paused))return null;if(this.resolve())return null;var bot=this.nextBot(),target=this.targetFor(bot),choice,result,dealt=0,profile,attackDamage;if(!bot||!target){this.resolve();return null;}choice=EA.Strategies[bot.strategy].choose(bot,target,this);if(!target.alive){target=this.targetFor(bot);if(!target){this.resolve();return null;}choice=EA.Strategies[bot.strategy].choose(bot,target,this);}result=EA.simulateShot(choice.equation,this.arena,this.bots,bot,this.config.friendlyFire);bot.shots+=1;bot.lastEquation=choice.equation.text();bot.distanceTotal+=result.minDistance;if(result.hit){profile=bot.archetypeData||{aggression:1};attackDamage=this.config.damage*(.88+.12*profile.aggression);if(bot.archetype==='berserker')attackDamage*=1+(1-bot.hp/bot.maxHp)*.3;dealt=result.hit.applyDamage(Math.round(attackDamage),bot);bot.damage+=dealt;if(result.hit.team!==bot.team){bot.hits+=1;this.teamStats[bot.team].hits+=1;}this.teamStats[bot.team].damage+=dealt;if(!result.hit.alive){bot.kills+=1;this.teamStats[bot.team].kills+=1;}}bot.memory.push({verticalError:target.y-result.impact.y,distance:result.minDistance});if(bot.memory.length>12)bot.memory.shift();this.turn+=1;this.current={bot:bot,target:target,choice:choice,result:result,dealt:dealt};this.history.push({turn:this.turn,bot:bot.name,archetype:bot.archetype,target:target.name,equation:choice.equation.text(),family:choice.equation.family,result:result.reason,distance:Math.round(result.minDistance),damage:dealt,fitness:choice.fitness||null});this.resolve();if(this.config.mode==='passo')this.paused=true;return this.current;};
  GameEngine.prototype.runFast=function(){var guard=0,limit=this.config.turnLimit+2;this.paused=false;while(!this.finished&&guard<limit){this.step(true);guard+=1;}return this.winner;};
  EA.battlePreset=function(config,count){var result=Object.assign({},config||{}),n=EA.clamp(count,1,40);result.botsA=n;result.botsB=n;result.turnLimit=Math.max(Number(result.turnLimit)||0,n*12);result.width=Math.max(Number(result.width)||0,n>=30?1600:n>=20?1400:1200);return clean(result);};
  EA.chaoticConfig=function(config){var result=EA.battlePreset(config,10);result.mapType='caos';result.density='alta';result.spawnMode='caos';result.obstacles=4;result.turnLimit=Math.max(result.turnLimit,240);return clean(result);};
  EA.DEFAULTS=defaults;EA.cleanConfig=clean;EA.GameEngine=GameEngine;
}(window.EA));
