(function (EA) {
  'use strict';
  function Renderer(canvas){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.progress=0;this.lastTurn=-1;this.camera=new EA.Camera();this.bindCamera();}
  Renderer.prototype.bindCamera=function(){var self=this,last=null;this.canvas.addEventListener('wheel',function(event){event.preventDefault();self.camera.changeZoom(event.deltaY<0?1.12:.89);},{passive:false});this.canvas.addEventListener('pointerdown',function(event){last={x:event.clientX,y:event.clientY};self.canvas.setPointerCapture(event.pointerId);});this.canvas.addEventListener('pointermove',function(event){if(!last)return;self.camera.pan(event.clientX-last.x,event.clientY-last.y);last={x:event.clientX,y:event.clientY};});this.canvas.addEventListener('pointerup',function(){last=null;});};
  Renderer.prototype.resize=function(arena){var d=Math.min(2,window.devicePixelRatio||1),w=this.canvas.clientWidth||900,h=w*arena.height/arena.width;this.canvas.style.height=h+'px';this.canvas.width=Math.round(w*d);this.canvas.height=Math.round(h*d);};
  Renderer.prototype.transform=function(arena){var sx=this.canvas.width/arena.width,sy=this.canvas.height/arena.height,z=this.camera.zoom;this.ctx.setTransform(sx*z,0,0,sy*z,-this.camera.x*sx*z,-this.camera.y*sy*z);};
  Renderer.prototype.drawGrid=function(arena){var c=this.ctx,i,step=arena.width>1400?100:50;c.fillStyle='#07101f';c.fillRect(0,0,arena.width,arena.height);c.lineWidth=1;c.strokeStyle='rgba(83,130,180,.14)';for(i=0;i<=arena.width;i+=step){c.beginPath();c.moveTo(i,0);c.lineTo(i,arena.ground);c.stroke();}for(i=0;i<=arena.ground;i+=step){c.beginPath();c.moveTo(0,i);c.lineTo(arena.width,i);c.stroke();}c.strokeStyle='rgba(126,160,200,.55)';c.beginPath();c.moveTo(0,arena.ground);c.lineTo(arena.width,arena.ground);c.moveTo(arena.width/2,0);c.lineTo(arena.width/2,arena.ground);c.stroke();c.fillStyle='#7086a8';c.font='10px monospace';c.textAlign='center';for(i=0;i<=arena.width;i+=step*2)c.fillText(String(i-arena.width/2),i,arena.ground+16);};
  Renderer.prototype.drawObstacle=function(obstacle){var c=this.ctx,colors={parede:'#263958',torre:'#2c3656',pilar:'#293f55',plataforma:'#243d50',rampa:'#33405c',bloco:'#202f49'};c.fillStyle=colors[obstacle.type]||colors.bloco;c.fillRect(obstacle.x,obstacle.y,obstacle.w,obstacle.h);c.strokeStyle=obstacle.type==='plataforma'?'#35a9b8':'#7467bd';c.strokeRect(obstacle.x,obstacle.y,obstacle.w,obstacle.h);if(obstacle.type==='torre'){c.fillStyle='#151f35';c.fillRect(obstacle.x+obstacle.w*.2,obstacle.y+12,obstacle.w*.6,8);}};
  Renderer.prototype.draw=function(game){var c=this.ctx,a=game.arena,i,b,cur=game.current,path,n,compact=game.bots.length>20,barWidth;c.setTransform(1,0,0,1,0,0);c.clearRect(0,0,this.canvas.width,this.canvas.height);this.transform(a);this.drawGrid(a);for(i=0;i<a.obstacles.length;i+=1)this.drawObstacle(a.obstacles[i]);for(i=0;i<game.bots.length;i+=1){b=game.bots[i];barWidth=compact?14:34;c.globalAlpha=b.alive?1:.18;c.fillStyle=b.color;c.beginPath();c.arc(b.x,b.y,b.radius,0,Math.PI*2);c.fill();if(cur&&(b===cur.bot||b===cur.target)){c.strokeStyle=b===cur.target?'#ffd166':'#fff';c.lineWidth=2;c.beginPath();c.arc(b.x,b.y,b.radius+5,0,Math.PI*2);c.stroke();}c.fillStyle='#eaf4ff';c.font=(compact?'6px':'9px')+' monospace';c.textAlign='center';c.fillText(b.id,b.x,b.y-b.radius-3);c.fillStyle='#263552';c.fillRect(b.x-barWidth/2,b.y+b.radius+2,barWidth,compact?2:3);c.fillStyle=b.color;c.fillRect(b.x-barWidth/2,b.y+b.radius+2,barWidth*b.hp/b.maxHp,compact?2:3);}c.globalAlpha=1;if(cur){path=cur.result.path;c.save();c.setLineDash([5,7]);c.strokeStyle='rgba(255,255,255,.28)';c.lineWidth=1;c.beginPath();for(i=0;i<path.length;i+=1){if(i)c.lineTo(path[i].x,path[i].y);else c.moveTo(path[i].x,path[i].y);}c.stroke();c.restore();n=Math.min(path.length,Math.max(2,Math.floor(this.progress)));c.strokeStyle=cur.bot.color;c.lineWidth=3;c.shadowBlur=9;c.shadowColor=cur.bot.color;c.beginPath();for(i=0;i<n;i+=1){if(i)c.lineTo(path[i].x,path[i].y);else c.moveTo(path[i].x,path[i].y);}c.stroke();c.shadowBlur=0;c.fillStyle='#ffd166';c.beginPath();c.arc(cur.result.impact.x,cur.result.impact.y,5,0,Math.PI*2);c.fill();}};
  Renderer.prototype.animate=function(game){if(game.turn!==this.lastTurn){this.lastTurn=game.turn;this.progress=0;}this.progress+=Math.max(2,game.config.speed*3);this.draw(game);};EA.Renderer=Renderer;
}(window.EA));
